-- These are the live plans used for the grid endpoints and the smart-count dashboard.

-- 1) List by view: default all-items for a seeded team.
EXPLAIN (ANALYZE, BUFFERS)
SELECT id, team_id, title, status, priority, assignee_id, due_at, version, updated_at
FROM work_items
WHERE team_id = (SELECT id FROM teams ORDER BY name LIMIT 1)
ORDER BY priority ASC, updated_at DESC, id ASC
LIMIT 50;

-- 2) List by view: assigned_to_me view for one user.
EXPLAIN (ANALYZE, BUFFERS)
SELECT id, team_id, title, status, priority, assignee_id, due_at, version, updated_at
FROM work_items
WHERE team_id = (SELECT id FROM teams ORDER BY name LIMIT 1)
  AND assignee_id = (SELECT id FROM users WHERE email = 'marcus@opsflow.local')
ORDER BY priority ASC, updated_at DESC, id ASC
LIMIT 50;

-- 3) Full-text-search variant used when the q filter is present.
EXPLAIN (ANALYZE, BUFFERS)
SELECT id, team_id, title, status, priority, assignee_id, due_at, version, updated_at
FROM work_items
WHERE team_id = (SELECT id FROM teams ORDER BY name LIMIT 1)
  AND search @@ websearch_to_tsquery('english', 'payment investigation')
ORDER BY priority ASC, updated_at DESC, id ASC
LIMIT 50;

-- 4) View counts as generated by the dashboard summary endpoint.
EXPLAIN (ANALYZE, BUFFERS)
SELECT
  count(*) FILTER (WHERE assignee_id = (SELECT id FROM users WHERE email = 'marcus@opsflow.local')) AS assigned_to_me,
  count(*) FILTER (WHERE assignee_id IS NULL AND status IN ('new', 'triaged')) AS team_unassigned,
  count(*) FILTER (WHERE priority <= 2 AND status NOT IN ('resolved', 'closed')) AS urgent,
  count(*) FILTER (WHERE status = 'pending_approval') AS waiting_approval,
  count(*) AS all_items
FROM work_items
WHERE team_id = (SELECT id FROM teams ORDER BY name LIMIT 1);

-- 5) Events by item, newest-first.
EXPLAIN (ANALYZE, BUFFERS)
SELECT id, item_id, type, created_at
FROM item_events
WHERE item_id = (SELECT id FROM work_items ORDER BY updated_at DESC LIMIT 1)
ORDER BY id DESC
LIMIT 25;
